// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_fA_BKkj1oDDymRsI7tEYHbZnchImvcU',
    appId: '1:952849238886:web:a7c32e6bcf9d52efb896a7',
    messagingSenderId: '952849238886',
    projectId: 'chat-31297',
    authDomain: 'chat-31297.firebaseapp.com',
    storageBucket: 'chat-31297.appspot.com',
    measurementId: 'G-6NBT2E4EHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMJCpZs0VvQcf7_niMVeNqqBvHeSD97WA',
    appId: '1:952849238886:android:a98e318e52de0acdb896a7',
    messagingSenderId: '952849238886',
    projectId: 'chat-31297',
    storageBucket: 'chat-31297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRP4DmJUVjK3zLMn6FS6eTlA6vDPUoVc',
    appId: '1:952849238886:ios:2442864b4013fbe7b896a7',
    messagingSenderId: '952849238886',
    projectId: 'chat-31297',
    storageBucket: 'chat-31297.appspot.com',
    iosClientId: '952849238886-c6p80lrg2cdiit0gblscnfdh2kh66jhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRP4DmJUVjK3zLMn6FS6eTlA6vDPUoVc',
    appId: '1:952849238886:ios:2442864b4013fbe7b896a7',
    messagingSenderId: '952849238886',
    projectId: 'chat-31297',
    storageBucket: 'chat-31297.appspot.com',
    iosClientId: '952849238886-c6p80lrg2cdiit0gblscnfdh2kh66jhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
